### ISSUE TITLE
Blank page with latest update

### ISSUE THREAD

**Issue by kerwindouglas** [hotio/petio#1]
I've been running the Petio hotio on my RPi 4 for about a year with no issues. But as of the latest build from Mar 29th 2022, results in a blank page. Logs do not contain any errors.  All I get is the following when loading the webapp in my browser.

![image](https://user-images.githubusercontent.com/431259/160836603-e18b38b8-252d-4af1-b605-c940affc39db.png)

I have reverted back to release-73b6417 from 6 days ago, and its working.

**Comment by jplivingston08** [comment]
Same here

**Comment by jonfairbanks** [comment]
@mrhotio Can you check on the lastest build of petio?

**Comment by mrhotio** [comment]
I'm on it, I've notified the pet devs about the issue....seems an update of nodejs breaks petio

**Comment by mrhotio** [comment]
I've rolled back the base image and thus also the nodejs version, so should be resolved for the moment....

**Comment by comanbo** [comment]
Working now. Thanks
